// SPDX-FileCopyrightText: Copyright 2025 Clever Design (Switzerland) GmbH
// SPDX-License-Identifier: Apache-2.0

#ifndef TINYPLATFORM_POSIX_CONFIG_H_
#define TINYPLATFORM_POSIX_CONFIG_H_

#define CONFIG_TINYPLATFORM_MAX_SUBSCRIBERS 64
#define CONFIG_TINYPLATFORM_MAX_BACKLOG 64
#define CONFIG_TINYPLATFORM_LOG 1

#endif // TINYPLATFORM_POSIX_CONFIG_H_
